TAXII_VERSION = 2.1

DEFAULT_LIMIT = 10

ACCEPT_TAXII_JSON = 'application/taxii+json'
HTTP_ACCEPT_KEY = 'HTTP_ACCEPT'
HTTP_CONTENT_TYPE = 'CONTENT_TYPE'
HTTP_CONTENT_LENGTH = 'CONTENT_LENGTH'
HTTP_AUTH_KEY = 'HTTP_AUTHORIZATION'

HTTP_RESPONSE_CONTENT_TYPE = 'application/taxii+json;version=2.1'

DEFAULT_VERSION = 'application/taxii+json;version=2.1'
DEFAULT_VERSIONS = [DEFAULT_VERSION]
DEFAULT_MEDIA_TYPE = 'application/stix+json;version=2.1'
DEFAULT_MEDIA_TYPES = [DEFAULT_MEDIA_TYPE]
DEFAULT_MAX_CONTENT_LENGTH = 104857600
