"""
Django settings for cti_repository_system project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import logging
from decouple import Csv, config, UndefinedValueError
from unipath import Path

logging.disable(logging.WARNING)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# LOGIN_URL
LOGIN_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# If you will use S-TIP in production mode, please change SECRET_KEY in .env file.
# Please keep same SECRET_KEY among S-TIP apps (for Single Sign On).
DEFAULT_SECRET_KEY = 'j%yjl@$v=xi6((y3!=bf3$n5)e)+af)*+syuia#co)1edp=dv-'
SECRET_KEY = config('SECRET_KEY', default=DEFAULT_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())
mysql_user = config('MYSQL_USER')
mysql_password = config('MYSQL_PASSWORD')
try:
    mysql_dbname = config('MYSQL_DBNAME')
except UndefinedValueError:
    mysql_dbname = 's_tip'
try:
    mysql_host = config('MYSQL_HOST')
except UndefinedValueError:
    mysql_host = 'localhost'
try:
    mysql_port = config('MYSQL_PORT')
except UndefinedValueError:
    mysql_port = '3306'

try:
    TIME_ZONE = config('TIME_ZONE')
except UndefinedValueError:
    TIME_ZONE = 'UTC'
try:
    cookie_domain_name = config('COOKIE_DOMAIN_NAME')
except UndefinedValueError:
    cookie_domain_name = None

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.boot.TXS21ConsoleBoot',
    'console.discovery',
    'console.api_root',
    'console.collection',
    'console.error',
    'ctirs',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

ROOT_URLCONF = 'console.urls'

SRC_DIR = os.path.join(BASE_DIR, 'src')
CONSOLE_DIR = os.path.join(SRC_DIR, 'console')
COMMON_PROJECT_DIR = '/opt/s-tip/common'

DIRS = [
    os.path.join(CONSOLE_DIR, 'dashboard/templates'),
    os.path.join(SRC_DIR, 'templates'),
    os.path.join(COMMON_PROJECT_DIR, 'src/templates'),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi_console.application'

# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': mysql_dbname,
        'USER': mysql_user,
        'PASSWORD': mysql_password,
        'HOST': mysql_host,
        'PORT': mysql_port,
    }
}
AUTH_USER_MODEL = 'ctirs.STIPUser'

# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'ja'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

PROJECT_DIR = Path(__file__).parent.parent
STATIC_ROOT = os.path.join(PROJECT_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(CONSOLE_DIR, 'static'),
    os.path.join(COMMON_PROJECT_DIR, 'src/static'),
]
STATIC_URL = '/static/'

SESSION_COOKIE_NAME = 'stip'
SESSION_COOKIE_DOMAIN = cookie_domain_name
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

APPEND_SLASH = False

USER_TABLE_JSON_PATH = os.path.join(BASE_DIR, 'src', 'auth', 'user_table.json')
